using System;
using System.Numerics;
using Content.Client.Resources;
using Content.Client.UserInterface.Controls;
using Content.Shared._Metro14.NpcTrader;
using Content.Shared.Nuke;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client._Metro14.NpcTrader
{
    [GenerateTypedNameReferences]
    public sealed partial class NpcTraderMenu : FancyWindow
    {
        [Dependency] private readonly IEntityManager _entityManager = default!;
        [Dependency] private readonly IPlayerManager _playerManager = default!;
        [Dependency] private readonly IPrototypeManager _prototype = default!;
        [Dependency] private readonly IResourceCache _resourceCache = default!;

        public event Action<NetEntity, string>? OnBuyButtonPressed;

        private EntityUid? _owner;
        private bool tagsExist = false;
        private string selectedId = "";
        private List<string> _tags = new() { "npc-trader-tag-all" }; // npc-trader-tag-all - это тег по умолчанию, скажем так...

        public NpcTraderMenu()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            ImageActionButton.OnPressed += _ => ImageActionButtonPressed();
        }

        public void SetEntity(EntityUid owner)
        {
            _owner = owner;
            selectedId = "";

            FillCatalog();
            LoadImage();
        }

        /// <summary>
        /// Обработчик кнопки "согласиться", который начинает проверку на возможность купить предметы.
        /// </summary>
        public void ImageActionButtonPressed()
        {
            if (_playerManager.LocalEntity != null && !string.IsNullOrWhiteSpace(selectedId))
            {
                var playerUid = (EntityUid)_playerManager.LocalEntity;

                OnBuyButtonPressed?.Invoke(_entityManager.GetNetEntity(playerUid), selectedId);
                selectedId = "";
                base.Close();
            }

            return;
        }

        /// <summary>
        /// Метод, который заполняет список возможных предложений у торговца.
        /// </summary>
        private void FillCatalog(string tag = "npc-trader-tag-all")
        {
            if (_owner == null)
                return;

            // получаем компонент торговца у владельца окна (то есть торговца)
            if (!_entityManager.TryGetComponent<NpcTraderComponent>(_owner, out var npcTraderComponent))
                return;

            // очищаем список предложений
            DynamicButtonList.RemoveAllChildren();

            // перебираем все предложения торговца
            foreach (var item in npcTraderComponent.ItemsInCatalog)
            {
                // проверяем, что предложение существует
                if (!_prototype.TryIndex<NpcTraderItemForCatalogPrototype>(item.Key, out var protoItemOfCatalog))
                    continue;

                if (!tagsExist)
                {
                    foreach (var prodTag in protoItemOfCatalog.ProductTags)
                    {
                        if (!_tags.Contains(prodTag))
                            _tags.Add(prodTag);
                    }

                    LoadTags();
                }

                if (!tag.Equals("npc-trader-tag-all"))
                {
                    if (!protoItemOfCatalog.ProductTags.Contains(tag))
                        continue;
                }

                // создаем кнопку для товара
                var button = new Button
                {
                    Margin = new Thickness(0, 0, 0, 2)
                };
                var container = new BoxContainer { Orientation = LayoutOrientation.Horizontal };

                // создаем иконку для кнопки
                if (!string.IsNullOrWhiteSpace(protoItemOfCatalog.IconId))
                {
                    if (!_prototype.TryIndex<EntityPrototype>(protoItemOfCatalog.IconId, out var tempProto))
                        continue;

                    var icon = new EntityPrototypeView
                    {
                        SetSize = new Vector2(32, 32),
                        VerticalAlignment = VAlignment.Center
                    };
                    icon.SetPrototype(protoItemOfCatalog.IconId);

                    container.AddChild(icon);
                }
                else if (!string.IsNullOrWhiteSpace(protoItemOfCatalog.IconPath))
                {
                    var texture = _resourceCache.GetTexture(protoItemOfCatalog.IconPath);

                    var iconTexture = new TextureRect
                    {
                        Texture = texture,
                        SetSize = new Vector2(32, 32),
                        Stretch = TextureRect.StretchMode.KeepCentered,
                    };
                    button.AddChild(iconTexture);
                }

                // создаем текст для кнопки
                var label = new Label
                {
                    Text = Loc.GetString(protoItemOfCatalog.Name),
                    HorizontalExpand = true,
                    VerticalAlignment = VAlignment.Center
                };

                // формируем корректное название кнопки
                if (item.Value == -1)
                    label.Text = Loc.GetString(protoItemOfCatalog.Name);
                else
                    label.Text = Loc.GetString(protoItemOfCatalog.Name) + " [" + item.Value + "]";

                container.AddChild(label);
                button.AddChild(container);

                button.AddStyleClass("ButtonSquare");
                button.OnPressed += args => OnButtonPressed(button, protoItemOfCatalog.ID);

                DynamicButtonList.AddChild(button);
            }
            tagsExist = true;
        }

        /// <summary>
        /// Метод для создания списка тегов предложений. 
        /// </summary>
        private void LoadTags()
        {
            DownTagsButtonList.RemoveAllChildren();

            foreach (var tag in _tags)
            {
                var button = new Button
                {
                    Margin = new Thickness(0, 0, 0, 2)
                };
                var container = new BoxContainer { Orientation = LayoutOrientation.Horizontal };

                var label = new Label
                {
                    Text = Loc.GetString(tag),
                    HorizontalExpand = true,
                    VerticalAlignment = VAlignment.Center,
                    HorizontalAlignment = HAlignment.Center
                };

                container.AddChild(label);
                button.AddChild(container);

                button.AddStyleClass("ButtonSquare");
                button.OnPressed += args => OnTagButtonPressed(button, tag);

                DownTagsButtonList.AddChild(button);
            }
        }

        /// <summary>
        /// Обработчик нажатия кнопки выбора тега.
        /// </summary>
        private void OnTagButtonPressed(Button button, string tag)
        {
            FillCatalog(tag);
        }

        /// <summary>
        /// Метод для загрузки ихображение торговца в диалоговом окне.
        /// </summary>
        private void LoadImage()
        {
            if (!_entityManager.TryGetComponent<NpcTraderComponent>(_owner, out var npcTraderComponent))
                return;

            var texture = _resourceCache.GetTexture(npcTraderComponent.PathToImage);
            DisplayImage.Texture = texture;
        }

        /// <summary>
        /// Обработчик нажатия кнопки-предложения.
        /// </summary>
        private void OnButtonPressed(Button button, string id)
        {
            if (!_prototype.TryIndex<NpcTraderItemForCatalogPrototype>(id, out var npcTraderItemForCatalogProto))
                return;

            CreateButton(npcTraderItemForCatalogProto.GivingItems, LeftButtonList);
            CreateButton(npcTraderItemForCatalogProto.TakingItems, RightButtonList);

            InfoTextField.Text = npcTraderItemForCatalogProto.Description;

            selectedId = id;
        }

        /// <summary>
        /// Метод создающий кнопки-пустышки, которые демонстрируют получаемые и отдаваемые предметы.
        /// </summary>
        private void CreateButton(Dictionary<string, int> dict, BoxContainer xamlContainer)
        {
            xamlContainer.RemoveAllChildren();

            foreach (var item in dict)
            {
                if (!_prototype.TryIndex<EntityPrototype>(item.Key, out var tempProto))
                    continue;

                string nameOfLabel = "";
                if (tempProto.Name != null)
                {
                    nameOfLabel = tempProto.Name + " [" + item.Value + "]";
                }
                else
                {
                    nameOfLabel = item.Key + " [" + item.Value + "]";
                }

                var button = new Button();
                var container = new BoxContainer { Orientation = LayoutOrientation.Horizontal };

                var icon = new EntityPrototypeView
                {
                    SetSize = new Vector2(32, 32),
                    VerticalAlignment = VAlignment.Center
                };
                icon.SetPrototype(item.Key);

                var label = new Label
                {
                    Text = nameOfLabel,
                    HorizontalExpand = true,
                    VerticalAlignment = VAlignment.Center
                };

                container.AddChild(icon);
                container.AddChild(label);
                button.AddChild(container);
                button.AddStyleClass("ButtonSquare");

                xamlContainer.AddChild(button);
            }
        }
    }
}
